---

kind: pipeline
name: default

steps:
  - name: install
    image: node:lts
    commands:
      - npm i

  - name: test
    image: node:lts
    commands:
      - npm test

  - name: build
    image: node:lts
    commands:
      - npm run build:production

  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_token
      email:
        from_secret: npm_email
